### PR TITLE
add QAFIRO file ripqp tuto 2

### PR DESCRIPTION
**Pull request by geoffroyleconte**
**Updates to Introduction to RipQP**

- [ ] Introduction to RipQP:
- [ ] Add missing QAFIRO file:
- Wait for the workflow, look at the [preview], and confirm:
  - [ ] The preview has your tutorial listed.
  - [ ] The preview looks like what you want.

[preview]: https://juliasmoothoptimizers.github.io/JSOTutorials.jl/
[Grammarly]: https://www.grammarly.com

### CODE REVIEW

**Comment by geoffroyleconte** [comment]
hmmm, this is still not working. @tmigot should I put QAFIRO.SIF somewhere else?

**Comment by tmigot** [comment]
Ok, so I think we also miss a mechanism to copy the files. For instance, if you have images, they have to be in a folder `figures` as added by 
https://github.com/JuliaSmoothOptimizers/JSOTutorials.jl/pull/56/files ( example here: https://github.com/JuliaSmoothOptimizers/JSOTutorials.jl/tree/main/tutorials/introduction-to-pdenlpmodels ).
So, we should also do the same for other files. Maybe a folder `assets` would work.

**Comment by tmigot** [comment]
@geoffroyleconte Can you move the file to a folder `assets` in `tutorials/introduction-to-ripqp`?

**Comment by geoffroyleconte** [comment]
@tmigot is there a way I can display the logs generated with `@info log_row(...)` ?

**Comment by tmigot** [comment]
@geoffroyleconte That's another good question, maybe if you use `https://docs.julialang.org/en/v1/stdlib/Logging/#Logging.ConsoleLogger` ?

**Comment by tmigot** [comment]
@abelsiqueira Any idea why the preview doesn't seem to copy the files in the folder `assets`?

**Comment by abelsiqueira** [comment]
It is being copied: https://github.com/JuliaSmoothOptimizers/JSOTutorials.jl/tree/gh-pages/introduction-to-ripqp/assets
Also, since the building/weaving is done at the original folder, it shouldn't be a problem.
So probably it is something related to the path. Since the build script is called from the root, I would not be surprised if the path is "tutorials/intro-...".

I think a better solution would be to use `download` to download the QAFIRO.SIF file from somewhere (https://raw.githubusercontent.com/JuliaSmoothOptimizers/RipQP.jl/main/test/QAFIRO.SIF for instance).
This way, it is also easy for the reader to follow the tutorial.

**Comment by tmigot** [comment]
Thanks @abelsiqueira for the feedback! Sorry, I think one of @geoffroyleconte 's commits triggered the correct build finally.

**Review by tmigot — APPROVED** [review]
Thanks @geoffroyleconte !

**Pull request merged**
